# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5eaa80bcbdefedfb93807d69f518b90c9ae682c1ca291c392f9f5efce8190d86730b0121941fbc097ff3dda6d44a61d6270dd2bca8dee9ecbd6256e1953f5fc0

test:
  secret_key_base: cdc9a9663200b04e4178691c07e476efc4534e5ce947638f785488f12481b239236971f70401ea207da49d79362453d26c5d32b2a731bd8c295cdf7e4ebb0765

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
